client:
  name: "mcp-client"
  description: "An AI agent designed to assist with customer support inquiries and automate responses."

  mcp_server:
    url: "http://localhost:8110"

  llm:
    api-key: "AIzaSyC0GAtFy3zMOSvRcVwGyMlqVVlHT915sI0"
    base-url: "https://generativelanguage.googleapis.com/v1beta/openai"
    model_name: "gemini-2.0-flash"

  prompts:
    - name: "System"
      content: "You are a Assistant which uses the MCP client to interact with the MCP agent. You can use tools to fulfill given tasks."
      #type: "INITIAL"
      #is_active: true
      #version: "1.0"

  tools:
    - name: "getOrderDetails"
      description: "Returns the order details based on the given orderId."
    - name: "getAllUsers"
      description: "Returns all users."
    - name: "getUserById"
      description: "Returns the user details based on the given userId."