openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
servers:
  - url: http://localhost:8000 # Assuming your FastAPI server runs on this port
paths:
  /users/{userId}:
    get:
      operationId: get_user_by_id_api_v1_users__userId__get
      summary: Get user by ID
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the user to retrieve
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  email:
                    type: string
        '404':
          description: User not found
